rebuild #14

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,11 +8,6 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Debug Environment
-        run: |
-          ls -la node_modules/.bin
-          echo $PATH
-
       - name: Deploy using ssh
         uses: appleboy/ssh-action@master
         with:
@@ -45,10 +40,4 @@ jobs:
                 fi
                 
                 # Instal dependensi npm
-                npm install --only=prod || { echo "npm install failed"; exit 1; }
-                
-                # Build aplikasi dengan Vite
-                node_modules/.bin/vite build || { echo "Vite build failed"; exit 1; }
-
-                # Jalankan aplikasi dengan Vite di background
-                nohup node_modules/.bin/vite --host 202.10.40.143 > /dev/null 2>&1 &
+                npm install || { echo "npm install failed"; exit 1; }
